import { useState, useEffect, useRef } from 'react'
import { Image as ImageIcon, Check, RefreshCw, Loader, AlertCircle, Download, ArrowLeft, Instagram, History, ChevronDown, ChevronUp, Clock } from 'lucide-react'
import { useProject } from '@contexts/ProjectContext'
import { imageEngine } from '@services/generation/imageEngine'
import InstagramModal from '@components/common/InstagramModal'
import './ImageGenerator.css'

// Helper: detect if a URL is a valid displayable image (not a stripped base64 marker)
const isValidImageUrl = (url) => {
    if (!url) return false
    if (url.includes('...[base64]')) return false  // stripped base64 marker
    return url.startsWith('data:image') || url.startsWith('http') || url.startsWith('/')
}

export default function ImageGenerator({ onNext, onBack }) {
    const { project, updateProject, saveProject } = useProject()

    // Initialize images: only load from context if they have valid displayable URLs
    // Initialize images: map saved images to their correct slide indices
    const [images, setImages] = useState(() => {
        const slideCount = project.content?.slides?.length || 0;
        const initial = Array(slideCount).fill(null).map((_, i) => ({
            slideIndex: i,
            status: 'pending',
            generationHistory: []
        }));

        const saved = project.finalImages || [];
        saved.forEach(img => {
            if (img.slideIndex !== undefined && img.slideIndex < slideCount) {
                initial[img.slideIndex] = {
                    ...img,
                    status: isValidImageUrl(img.url) ? 'complete' : (img.status || 'pending')
                };
            }
        });
        return initial;
    })

    const [generating, setGenerating] = useState(false)
    const [error, setError] = useState(null)
    const [selectedImage, setSelectedImage] = useState(null)
    const [previewIndex, setPreviewIndex] = useState(null)
    const [finishLoading, setFinishLoading] = useState(false)
    // Track which slides have expanded history
    const [expandedHistory, setExpandedHistory] = useState({})
    const hasAutoGenerated = useRef(false)

    useEffect(() => {
        if (hasAutoGenerated.current || generating) return

        const slideCount = project.content?.slides?.length || 0;
        if (slideCount === 0) return;

        const saved = project.finalImages || []
        const validImagesCount = saved.filter(img => isValidImageUrl(img.url)).length;

        // If no images at all, auto-generate
        if (validImagesCount === 0 && slideCount > 0) {
            hasAutoGenerated.current = true
            generateAll()
        } else if (images.length === 0 || images.every(img => img.status === 'pending')) {
            // Re-sync if we have partial data and haven't initialized yet
            const initial = Array(slideCount).fill(null).map((_, i) => ({
                slideIndex: i,
                status: 'pending',
                generationHistory: []
            }));

            saved.forEach(img => {
                if (img.slideIndex !== undefined && img.slideIndex < slideCount) {
                    initial[img.slideIndex] = {
                        ...img,
                        status: isValidImageUrl(img.url) ? 'complete' : (img.status || 'pending')
                    };
                }
            });
            setImages(initial);
        }
    }, [project.finalImages, project.content?.slides])

    // Sync valid images from context if they load later (e.g. from hydration)
    useEffect(() => {
        const saved = project.finalImages || []
        const slideCount = project.content?.slides?.length || 0;

        if (saved.length > 0 && slideCount > 0) {
            setImages(prev => {
                const next = [...prev];
                // Ensure length matches
                while (next.length < slideCount) {
                    next.push({ slideIndex: next.length, status: 'pending', generationHistory: [] });
                }

                saved.forEach(img => {
                    if (img.slideIndex !== undefined && img.slideIndex < slideCount) {
                        // Only update if the saved version is more complete or significantly different
                        const current = next[img.slideIndex];
                        if (!isValidImageUrl(current?.url) && isValidImageUrl(img.url)) {
                            next[img.slideIndex] = {
                                ...img,
                                status: 'complete'
                            };
                        }
                    }
                });
                return next;
            });
        }
    }, [project.finalImages])

    const generateAll = async () => {
        if (generating) return
        setGenerating(true)
        setError(null)

        try {
            const placeholders = project.content.slides.map((_, i) => ({
                slideIndex: i,
                status: 'loading',
                generationHistory: images[i]?.generationHistory || []
            }))
            setImages(placeholders)

            const results = await imageEngine.generateAllImages(project)

            const finalImages = results.map((r, i) => {
                const prev = images[i] || {}
                const slide = project.content?.slides?.[i] || {}
                // Move current image to history if it was valid
                const prevHistory = prev.generationHistory || []
                const newHistory = prev.url && isValidImageUrl(prev.url)
                    ? [{ url: prev.url, prompt: prev.prompt, generatedAt: new Date().toISOString() }, ...prevHistory]
                    : prevHistory

                return {
                    slideIndex: r.slideIndex,
                    url: r.imageUrl,
                    prompt: r.prompt,
                    displayCaption: slide.heading || slide.text || slide.subtext || r.prompt,
                    status: r.status === 'success' ? 'complete' : 'error',
                    error: r.error,
                    generationHistory: newHistory
                }
            })

            setImages(finalImages)
            updateProject({ finalImages })

            // Auto-save the generated images immediately so they aren't lost on navigation/refresh
            if (project.id) {
                console.log('💾 Auto-saving generated images...');
                saveProject({ finalImages, status: 'draft' }).catch(err => {
                    console.error('Auto-save of images failed:', err);
                });
            }

        } catch (err) {
            console.error('Generation failed:', err)
            setError(err.message)
        } finally {
            setGenerating(false)
        }
    }

    const regenerateSingle = async (index) => {
        const currentImg = images[index] || {}
        const slide = project.content?.slides?.[index] || {}
        // Save current to history before regenerating
        const prevHistory = currentImg.generationHistory || []
        const updatedHistory = currentImg.url && isValidImageUrl(currentImg.url)
            ? [{ url: currentImg.url, prompt: currentImg.prompt, generatedAt: new Date().toISOString() }, ...prevHistory]
            : prevHistory

        const newImages = [...images]
        newImages[index] = { ...currentImg, status: 'loading', generationHistory: updatedHistory }
        setImages(newImages)

        try {
            const result = await imageEngine.generateSingleImage(project, index)

            newImages[index] = {
                slideIndex: index,
                url: result.imageUrl,
                prompt: result.prompt,
                displayCaption: slide.heading || slide.text || result.prompt,
                status: 'complete',
                generationHistory: updatedHistory
            }

            setImages([...newImages])
            updateProject({ finalImages: newImages })

            // Auto-save the regenerated slide
            if (project.id) {
                saveProject({ finalImages: newImages, status: 'draft' }).catch(err => {
                    console.error('Auto-save of regenerated slide failed:', err);
                });
            }

        } catch (err) {
            console.error(`Slide ${index + 1} regeneration failed:`, err)
            const updated = [...newImages]
            updated[index] = { ...updated[index], status: 'error', error: err.message }
            setImages(updated)
        }
    }

    const handleFinish = async () => {
        if (finishLoading) return
        setFinishLoading(true)
        setError(null)
        try {
            const saved = await saveProject({
                status: 'completed',
                finalImages: images
            })
            // Pass project ID as navigation depends on context hydration which can be slow
            const projectId = (saved && (saved._id || saved.id)) || project.id;
            onNext(projectId)
        } catch (err) {
            console.error('Failed to finalize project:', err)
            setError(`Failed to save: ${err.message}. Your images are still available — try again.`)
            setFinishLoading(false)
        }
    }

    const forceDownload = async (url, filename) => {
        try {
            const response = await fetch(url)
            const blob = await response.blob()
            const blobUrl = window.URL.createObjectURL(blob)
            const link = document.createElement('a')
            link.href = blobUrl
            link.download = filename || 'instaGen-image.png'
            document.body.appendChild(link)
            link.click()
            document.body.removeChild(link)
            window.URL.revokeObjectURL(blobUrl)
        } catch (err) {
            console.error('Download failed:', err)
            // Fallback for cross-origin if fetch fails
            window.open(url, '_blank')
        }
    }

    const toggleHistory = (index) => {
        setExpandedHistory(prev => ({ ...prev, [index]: !prev[index] }))
    }

    const readableImages = images.filter(img => isValidImageUrl(img.url))
    const allComplete = images.length > 0 && images.every(img => img.status === 'complete' || img.status === 'error')
    const anyLoading = images.some(img => img.status === 'loading')

    if (!project.visualPlan) {
        return (
            <div className="image-generator">
                <div className="preview-empty">
                    <ImageIcon size={48} />
                    <h3>No Visual Plan</h3>
                    <p>Please complete visual planning first</p>
                    {onBack && (
                        <button className="btn-secondary" onClick={onBack} style={{ marginTop: '1rem' }}>
                            <ArrowLeft size={20} />
                            Back
                        </button>
                    )}
                </div>
            </div>
        )
    }

    return (
        <div className="image-generator">
            <div className="preview-header">
                <div className="header-content">
                    <ImageIcon className="header-icon" />
                    <div>
                        <h2>Generation Studio</h2>
                        <p>
                            {generating
                                ? `Generating ${project.content.slides.length} slides...`
                                : `${readableImages.length} of ${project.content.slides.length} slides ready`
                            }
                        </p>
                    </div>
                </div>
                <div className="header-actions">
                    {onBack && (
                        <button className="btn-secondary" onClick={onBack} disabled={generating}>
                            <ArrowLeft size={18} />
                            Back
                        </button>
                    )}
                    <button
                        className="btn-secondary"
                        onClick={generateAll}
                        disabled={generating}
                    >
                        <RefreshCw size={18} className={generating ? 'spin' : ''} />
                        {generating ? 'Generating...' : 'Regenerate All'}
                    </button>
                    <button
                        className="btn-primary"
                        onClick={handleFinish}
                        disabled={generating || anyLoading || finishLoading || readableImages.length === 0}
                    >
                        {finishLoading
                            ? <><Loader size={18} className="spin" /> Saving...</>
                            : <><Check size={18} /> Finalize Project</>
                        }
                    </button>
                </div>
            </div>

            {error && (
                <div className="error-banner">
                    <AlertCircle size={20} />
                    <span>{error}</span>
                </div>
            )}

            <div className="images-grid">
                {project.content.slides.map((slide, index) => {
                    const img = images[index] || { status: 'pending' }
                    const hasHistory = img.generationHistory?.length > 0
                    const isHistExpanded = expandedHistory[index]

                    return (
                        <div key={index} className="image-card">
                            <div className="card-header">
                                <span className="slide-badge">Slide {index + 1}</span>
                                <span className="intent-badge">{slide.intent}</span>
                            </div>

                            <div className="image-container">
                                {img.status === 'loading' ? (
                                    <div className="loading-overlay">
                                        <Loader className="spin" size={32} />
                                        <span>Generating...</span>
                                    </div>
                                ) : img.status === 'error' ? (
                                    <div className="error-overlay">
                                        <AlertCircle size={32} />
                                        <span>Failed</span>
                                        <button onClick={() => regenerateSingle(index)}>Retry</button>
                                    </div>
                                ) : isValidImageUrl(img.url) ? (
                                    <img
                                        src={img.url}
                                        alt={`Slide ${index + 1}`}
                                        onClick={() => setSelectedImage(img)}
                                    />
                                ) : (
                                    <div className="placeholder-overlay">
                                        <ImageIcon size={32} />
                                        <span>Waiting...</span>
                                    </div>
                                )}
                            </div>

                            <div className="card-content">
                                <h4>{slide.heading}</h4>
                                <p>{slide.subtext}</p>
                            </div>

                            <div className="card-actions">
                                <button
                                    className="btn-icon"
                                    onClick={() => regenerateSingle(index)}
                                    title="Regenerate this slide"
                                    disabled={img.status === 'loading' || generating}
                                >
                                    <RefreshCw size={16} />
                                </button>
                                {isValidImageUrl(img.url) && (
                                    <>
                                        <button
                                            className="btn-icon"
                                            onClick={() => setPreviewIndex(index)}
                                            title="Instagram Preview"
                                        >
                                            <Instagram size={16} />
                                        </button>
                                        <button
                                            className="btn-icon"
                                            onClick={() => forceDownload(img.url, `slide-${index + 1}.png`)}
                                            title="Download"
                                        >
                                            <Download size={16} />
                                        </button>
                                    </>
                                )}
                                {hasHistory && (
                                    <button
                                        className="btn-icon history-toggle"
                                        onClick={() => toggleHistory(index)}
                                        title="View generation history"
                                    >
                                        <History size={16} />
                                        <span className="history-count">{img.generationHistory.length}</span>
                                    </button>
                                )}
                            </div>

                            {/* Generation History Panel */}
                            {hasHistory && isHistExpanded && (
                                <div className="generation-history">
                                    <div className="history-header">
                                        <Clock size={14} />
                                        <span>Previous Generations ({img.generationHistory.length})</span>
                                        <button className="btn-icon sm" onClick={() => toggleHistory(index)}>
                                            <ChevronUp size={14} />
                                        </button>
                                    </div>
                                    <div className="history-strip">
                                        {img.generationHistory.map((h, hIdx) => (
                                            <div key={hIdx} className="history-item">
                                                {isValidImageUrl(h.url) ? (
                                                    <div className="history-thumb-wrapper">
                                                        <img
                                                            src={h.url}
                                                            alt={`v${img.generationHistory.length - hIdx}`}
                                                            title={`Version ${img.generationHistory.length - hIdx} — click to view`}
                                                            onClick={() => setSelectedImage(h)}
                                                        />
                                                        <button
                                                            className="mini-history-download"
                                                            onClick={(e) => { e.stopPropagation(); forceDownload(h.url, `slide-${index + 1}-v${img.generationHistory.length - hIdx}.png`); }}
                                                            title="Download this version"
                                                        >
                                                            <Download size={12} />
                                                        </button>
                                                    </div>
                                                ) : (
                                                    <div className="history-item-placeholder">
                                                        <ImageIcon size={16} />
                                                    </div>
                                                )}
                                                <span className="history-label">v{img.generationHistory.length - hIdx}</span>
                                            </div>
                                        ))}
                                    </div>
                                </div>
                            )}

                            {/* Show collapsed history hint */}
                            {hasHistory && !isHistExpanded && (
                                <button className="history-hint" onClick={() => toggleHistory(index)}>
                                    <History size={12} />
                                    {img.generationHistory.length} previous generation{img.generationHistory.length !== 1 ? 's' : ''}
                                    <ChevronDown size={12} />
                                </button>
                            )}
                        </div>
                    )
                })}
            </div>

            {/* Instagram Preview Modal */}
            <InstagramModal
                isOpen={previewIndex !== null}
                onClose={() => setPreviewIndex(null)}
                images={images.filter(img => isValidImageUrl(img.url))}
                brandName={project.brandName}
                initialIndex={previewIndex || 0}
            />

            {/* Lightbox for full screen viewing */}
            {selectedImage && (
                <div className="lightbox" onClick={() => setSelectedImage(null)}>
                    <div className="lightbox-content" onClick={e => e.stopPropagation()}>
                        <button className="close-btn" onClick={() => setSelectedImage(null)}>&times;</button>
                        <img src={selectedImage.url} alt="Full screen preview" />
                        <div className="lightbox-caption">
                            <div className="caption-actions">
                                <button
                                    onClick={() => forceDownload(selectedImage.url, 'instaGen-slide.png')}
                                    className="btn btn-primary lightbox-download"
                                >
                                    <Download size={18} />
                                    Download Image
                                </button>
                            </div>
                            <div className="caption-section">
                                <strong>Content:</strong>
                                <p>{selectedImage.displayCaption || 'Generated Image'}</p>
                            </div>
                            <div className="caption-section">
                                <strong>AI Prompt:</strong>
                                <p className="tech-prompt">{selectedImage.prompt}</p>
                            </div>
                        </div>
                    </div>
                </div>
            )}
        </div>
    )
}
