import { useState, useEffect, useRef } from 'react'
import { Image as ImageIcon, Check, RefreshCw, Loader, AlertCircle, Download, ArrowLeft, Instagram, History, ChevronDown, ChevronUp, Clock } from 'lucide-react'
import { useProject } from '@contexts/ProjectContext'
import { imageEngine } from '@services/generation/imageEngine'
import InstagramModal from '@components/common/InstagramModal'
import './ImageGenerator.css'

// Helper: detect if a URL is a valid displayable image (not a stripped base64 marker)
const isValidImageUrl = (url) => {
    if (!url) return false
    if (url.includes('...[base64]')) return false  // stripped base64 marker
    return url.startsWith('data:image') || url.startsWith('http') || url.startsWith('/')
}

export default function ImageGenerator({ onNext, onBack }) {
    const { project, updateProject, saveProject } = useProject()

    // Initialize images: only load from context if they have valid displayable URLs
    const [images, setImages] = useState(() => {
        const saved = project.finalImages || []
        if (saved.length > 0 && saved.some(img => isValidImageUrl(img.url))) {
            return saved
        }
        return []
    })

    const [generating, setGenerating] = useState(false)
    const [error, setError] = useState(null)
    const [selectedImage, setSelectedImage] = useState(null)
    const [previewIndex, setPreviewIndex] = useState(null)
    const [finishLoading, setFinishLoading] = useState(false)
    // Track which slides have expanded history
    const [expandedHistory, setExpandedHistory] = useState({})
    const hasAutoGenerated = useRef(false)

    useEffect(() => {
        if (hasAutoGenerated.current || generating) return

        const saved = project.finalImages || []
        // Check if images are already present (avoid re-generation)
        const hasValidImages = saved.length > 0 && saved.some(img => isValidImageUrl(img.url))

        if (!hasValidImages && project.content?.slides?.length > 0) {
            hasAutoGenerated.current = true
            generateAll()
        } else if (hasValidImages && images.length === 0) {
            setImages(saved)
        }
    }, [project.finalImages, project.content?.slides])

    // Sync valid images from context if they load later
    useEffect(() => {
        const saved = project.finalImages || []
        if (saved.some(img => isValidImageUrl(img.url)) && images.length === 0) {
            setImages(saved)
        }
    }, [project.finalImages])

    const generateAll = async () => {
        if (generating) return
        setGenerating(true)
        setError(null)

        try {
            const placeholders = project.content.slides.map((_, i) => ({
                slideIndex: i,
                status: 'loading',
                generationHistory: images[i]?.generationHistory || []
            }))
            setImages(placeholders)

            const results = await imageEngine.generateAllImages(project)

            const finalImages = results.map((r, i) => {
                const prev = images[i] || {}
                const slide = project.content?.slides?.[i] || {}
                // Move current image to history if it was valid
                const prevHistory = prev.generationHistory || []
                const newHistory = prev.url && isValidImageUrl(prev.url)
                    ? [{ url: prev.url, prompt: prev.prompt, generatedAt: new Date().toISOString() }, ...prevHistory]
                    : prevHistory

                return {
                    slideIndex: r.slideIndex,
                    url: r.imageUrl,
                    prompt: r.prompt,
                    displayCaption: slide.heading || slide.text || r.prompt,
                    status: r.status === 'success' ? 'complete' : 'error',
                    error: r.error,
                    generationHistory: newHistory
                }
            })

            setImages(finalImages)
            updateProject({ finalImages })

        } catch (err) {
            console.error('Generation failed:', err)
            setError(err.message)
        } finally {
            setGenerating(false)
        }
    }

    const regenerateSingle = async (index) => {
        const currentImg = images[index] || {}
        const slide = project.content?.slides?.[index] || {}
        // Save current to history before regenerating
        const prevHistory = currentImg.generationHistory || []
        const updatedHistory = currentImg.url && isValidImageUrl(currentImg.url)
            ? [{ url: currentImg.url, prompt: currentImg.prompt, generatedAt: new Date().toISOString() }, ...prevHistory]
            : prevHistory

        const newImages = [...images]
        newImages[index] = { ...currentImg, status: 'loading', generationHistory: updatedHistory }
        setImages(newImages)

        try {
            const result = await imageEngine.generateSingleImage(project, index)

            newImages[index] = {
                slideIndex: index,
                url: result.imageUrl,
                prompt: result.prompt,
                displayCaption: slide.heading || slide.text || result.prompt,
                status: 'complete',
                generationHistory: updatedHistory
            }

            setImages([...newImages])
            updateProject({ finalImages: newImages })

        } catch (err) {
            console.error(`Slide ${index + 1} regeneration failed:`, err)
            const updated = [...newImages]
            updated[index] = { ...updated[index], status: 'error', error: err.message }
            setImages(updated)
        }
    }

    const handleFinish = async () => {
        if (finishLoading) return
        setFinishLoading(true)
        setError(null)
        try {
            const saved = await saveProject({
                status: 'completed',
                finalImages: images
            })
            // Pass project ID as navigation depends on context hydration which can be slow
            const projectId = (saved && (saved._id || saved.id)) || project.id;
            onNext(projectId)
        } catch (err) {
            console.error('Failed to finalize project:', err)
            setError(`Failed to save: ${err.message}. Your images are still available — try again.`)
            setFinishLoading(false)
        }
    }

    const toggleHistory = (index) => {
        setExpandedHistory(prev => ({ ...prev, [index]: !prev[index] }))
    }

    const readableImages = images.filter(img => isValidImageUrl(img.url))
    const allComplete = images.length > 0 && images.every(img => img.status === 'complete' || img.status === 'error')
    const anyLoading = images.some(img => img.status === 'loading')

    if (!project.visualPlan) {
        return (
            <div className="image-generator">
                <div className="preview-empty">
                    <ImageIcon size={48} />
                    <h3>No Visual Plan</h3>
                    <p>Please complete visual planning first</p>
                    {onBack && (
                        <button className="btn-secondary" onClick={onBack} style={{ marginTop: '1rem' }}>
                            <ArrowLeft size={20} />
                            Back
                        </button>
                    )}
                </div>
            </div>
        )
    }

    return (
        <div className="image-generator">
            <div className="preview-header">
                <div className="header-content">
                    <ImageIcon className="header-icon" />
                    <div>
                        <h2>Generation Studio</h2>
                        <p>
                            {generating
                                ? `Generating ${project.content.slides.length} slides...`
                                : `${readableImages.length} of ${project.content.slides.length} slides ready`
                            }
                        </p>
                    </div>
                </div>
                <div className="header-actions">
                    {onBack && (
                        <button className="btn-secondary" onClick={onBack} disabled={generating}>
                            <ArrowLeft size={18} />
                            Back
                        </button>
                    )}
                    <button
                        className="btn-secondary"
                        onClick={generateAll}
                        disabled={generating}
                    >
                        <RefreshCw size={18} className={generating ? 'spin' : ''} />
                        {generating ? 'Generating...' : 'Regenerate All'}
                    </button>
                    <button
                        className="btn-primary"
                        onClick={handleFinish}
                        disabled={generating || anyLoading || finishLoading || readableImages.length === 0}
                    >
                        {finishLoading
                            ? <><Loader size={18} className="spin" /> Saving...</>
                            : <><Check size={18} /> Finalize Project</>
                        }
                    </button>
                </div>
            </div>

            {error && (
                <div className="error-banner">
                    <AlertCircle size={20} />
                    <span>{error}</span>
                </div>
            )}

            <div className="images-grid">
                {project.content.slides.map((slide, index) => {
                    const img = images[index] || { status: 'pending' }
                    const hasHistory = img.generationHistory?.length > 0
                    const isHistExpanded = expandedHistory[index]

                    return (
                        <div key={index} className="image-card">
                            <div className="card-header">
                                <span className="slide-badge">Slide {index + 1}</span>
                                <span className="intent-badge">{slide.intent}</span>
                            </div>

                            <div className="image-container">
                                {img.status === 'loading' ? (
                                    <div className="loading-overlay">
                                        <Loader className="spin" size={32} />
                                        <span>Generating...</span>
                                    </div>
                                ) : img.status === 'error' ? (
                                    <div className="error-overlay">
                                        <AlertCircle size={32} />
                                        <span>Failed</span>
                                        <button onClick={() => regenerateSingle(index)}>Retry</button>
                                    </div>
                                ) : isValidImageUrl(img.url) ? (
                                    <img
                                        src={img.url}
                                        alt={`Slide ${index + 1}`}
                                        onClick={() => setSelectedImage(img)}
                                    />
                                ) : (
                                    <div className="placeholder-overlay">
                                        <ImageIcon size={32} />
                                        <span>Waiting...</span>
                                    </div>
                                )}
                            </div>

                            <div className="card-content">
                                <h4>{slide.heading}</h4>
                                <p>{slide.subtext}</p>
                            </div>

                            <div className="card-actions">
                                <button
                                    className="btn-icon"
                                    onClick={() => regenerateSingle(index)}
                                    title="Regenerate this slide"
                                    disabled={img.status === 'loading' || generating}
                                >
                                    <RefreshCw size={16} />
                                </button>
                                {isValidImageUrl(img.url) && (
                                    <>
                                        <button
                                            className="btn-icon"
                                            onClick={() => setPreviewIndex(index)}
                                            title="Instagram Preview"
                                        >
                                            <Instagram size={16} />
                                        </button>
                                        <a
                                            href={img.url}
                                            download={`slide-${index + 1}.png`}
                                            className="btn-icon"
                                            title="Download"
                                        >
                                            <Download size={16} />
                                        </a>
                                    </>
                                )}
                                {hasHistory && (
                                    <button
                                        className="btn-icon history-toggle"
                                        onClick={() => toggleHistory(index)}
                                        title="View generation history"
                                    >
                                        <History size={16} />
                                        <span className="history-count">{img.generationHistory.length}</span>
                                    </button>
                                )}
                            </div>

                            {/* Generation History Panel */}
                            {hasHistory && isHistExpanded && (
                                <div className="generation-history">
                                    <div className="history-header">
                                        <Clock size={14} />
                                        <span>Previous Generations ({img.generationHistory.length})</span>
                                        <button className="btn-icon sm" onClick={() => toggleHistory(index)}>
                                            <ChevronUp size={14} />
                                        </button>
                                    </div>
                                    <div className="history-strip">
                                        {img.generationHistory.map((h, hi) => (
                                            <div key={hi} className="history-item">
                                                {isValidImageUrl(h.url) ? (
                                                    <img
                                                        src={h.url}
                                                        alt={`v${img.generationHistory.length - hi}`}
                                                        title={`Version ${img.generationHistory.length - hi} — click to expand`}
                                                        onClick={() => setSelectedImage(h)}
                                                    />
                                                ) : (
                                                    <div className="history-item-placeholder">
                                                        <ImageIcon size={16} />
                                                    </div>
                                                )}
                                                <span className="history-label">v{img.generationHistory.length - hi}</span>
                                            </div>
                                        ))}
                                    </div>
                                </div>
                            )}

                            {/* Show collapsed history hint */}
                            {hasHistory && !isHistExpanded && (
                                <button className="history-hint" onClick={() => toggleHistory(index)}>
                                    <History size={12} />
                                    {img.generationHistory.length} previous generation{img.generationHistory.length !== 1 ? 's' : ''}
                                    <ChevronDown size={12} />
                                </button>
                            )}
                        </div>
                    )
                })}
            </div>

            {/* Instagram Preview Modal */}
            <InstagramModal
                isOpen={previewIndex !== null}
                onClose={() => setPreviewIndex(null)}
                images={images.filter(img => isValidImageUrl(img.url))}
                brandName={project.brandName}
                initialIndex={previewIndex || 0}
            />

            {/* Lightbox for full screen viewing */}
            {selectedImage && (
                <div className="lightbox" onClick={() => setSelectedImage(null)}>
                    <div className="lightbox-content" onClick={e => e.stopPropagation()}>
                        <button className="close-btn" onClick={() => setSelectedImage(null)}>&times;</button>
                        <img src={selectedImage.url} alt="Full screen preview" />
                        <div className="lightbox-caption">
                            <div className="caption-section">
                                <strong>Content:</strong>
                                <p>{selectedImage.displayCaption || 'Generated Image'}</p>
                            </div>
                            <div className="caption-section">
                                <strong>AI Prompt:</strong>
                                <p className="tech-prompt">{selectedImage.prompt}</p>
                            </div>
                        </div>
                    </div>
                </div>
            )}
        </div>
    )
}
